from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from kleva.ir.model import ReturnStmt
from kleva.ir.render import value_expr
from kleva.kernel import ProgramInput, build_program_model


class KernelProgramTests(unittest.TestCase):
    def test_build_program_model_collects_clang_ir_contracts_and_types(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            header = root / "api.h"
            source = root / "api.c"

            header.write_text(
                """
typedef struct Item {
    int value;
} Item;

/*@
    behavior valid:
        assumes \\valid(item);
        ensures \\result == 0 || \\result == -1;
*/
int use_item(Item *item);
""",
                encoding="utf-8",
            )
            source.write_text(
                """
#include "api.h"

int use_item(Item *item) {
    if (!item) {
        return -1;
    }
    return item->value;
}
""",
                encoding="utf-8",
            )

            model = build_program_model(
                ProgramInput(
                    header_path=header,
                    source_path=str(source),
                    include_dir=str(root),
                )
            )

        self.assertFalse(model.fallback_used)
        self.assertEqual([func.name for func in model.functions], ["use_item"])
        self.assertIn("use_item", model.acsl_specs)
        self.assertIn("use_item", model.function_irs)
        self.assertIn("use_item", model.function_decls)
        self.assertTrue(model.type_catalog.is_complete_struct("Item"))

    def test_build_program_model_reports_explicit_fallback_mode(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            header = root / "api.h"
            source = root / "api.c"

            header.write_text("int use_value(int value);\n", encoding="utf-8")
            source.write_text(
                """
#include "api.h"

int use_value(int value) {
    return value;
}
""",
                encoding="utf-8",
            )

            model = build_program_model(
                ProgramInput(
                    header_path=header,
                    source_path=str(source),
                    include_dir=str(root),
                    ir_backend="off",
                )
            )

        self.assertTrue(model.fallback_used)
        self.assertTrue(model.used_source_metadata_fallback)
        self.assertIn("use_value", model.function_decls)
        self.assertIsNotNone(model.source_text_for_fallbacks())
        self.assertTrue(any(diag.backend == "source-fallback" for diag in model.diagnostics))

    def test_program_model_reports_candidate_scoped_regex_fallback_fact(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            header = root / "api.h"
            source = root / "api.c"

            header.write_text("int use_value(int value);\n", encoding="utf-8")
            source.write_text(
                """
#include "api.h"

int use_value(int value) {
    return value;
}
""",
                encoding="utf-8",
            )

            model = build_program_model(
                ProgramInput(
                    header_path=header,
                    source_path=str(source),
                    include_dir=str(root),
                    shaping_features=frozenset({"regex-fallbacks"}),
                )
            )

        facts = model.fallback_fact_dicts(
            "use_value",
            candidate_name="source_branch",
            candidate_origin="regex",
        )

        self.assertTrue(any(fact["scope"] == "function" for fact in facts))
        self.assertIn({
            "kind": "fallback",
            "scope": "candidate",
            "function": "use_value",
            "candidate": "source_branch",
            "reason": "candidate generated by regex/source-text shaper",
        }, facts)

    def test_build_program_model_merges_extra_source_function_ir(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            header = root / "api.h"
            source = root / "api.c"
            helper = root / "helper.c"

            header.write_text("int api(int *item);\n", encoding="utf-8")
            source.write_text(
                """
#include "api.h"
int helper(int *item);
int api(int *item) {
    return helper(item);
}
""",
                encoding="utf-8",
            )
            helper.write_text(
                """
int helper(int *item) {
    *item = 1;
    return 0;
}
""",
                encoding="utf-8",
            )

            model = build_program_model(
                ProgramInput(
                    header_path=header,
                    source_path=str(source),
                    include_dir=str(root),
                    extra_sources=(str(helper),),
                )
            )

        self.assertIn("helper", model.function_irs)
        self.assertGreater(len(model.function_irs["helper"].statements), 0)

    def test_build_program_model_can_target_primary_source_static_functions(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            header = root / "api.h"
            source = root / "api.c"
            dep = root / "dep.c"

            header.write_text(
                """
static int header_helper(int value) {
    return value + 10;
}

int api(int value);
""",
                encoding="utf-8",
            )
            source.write_text(
                """
#include "api.h"

static int local_helper(int value) {
    return value + 1;
}

int api(int value) {
    return local_helper(value);
}
""",
                encoding="utf-8",
            )
            dep.write_text(
                """
int dependency_helper(int value) {
    return value - 1;
}
""",
                encoding="utf-8",
            )

            public_model = build_program_model(
                ProgramInput(
                    header_path=header,
                    source_path=str(source),
                    include_dir=str(root),
                    extra_sources=(str(dep),),
                )
            )
            internal_model = build_program_model(
                ProgramInput(
                    header_path=header,
                    source_path=str(source),
                    include_dir=str(root),
                    extra_sources=(str(dep),),
                    include_static_functions=True,
                )
            )

        self.assertEqual([func.name for func in public_model.functions], ["api"])
        self.assertIn("local_helper", internal_model.function_irs)
        self.assertIn("header_helper", internal_model.function_irs)
        self.assertIn("dependency_helper", internal_model.function_irs)
        self.assertEqual([func.name for func in internal_model.public_functions], ["api"])
        self.assertEqual([func.name for func in internal_model.internal_functions], ["local_helper"])
        self.assertEqual([func.name for func in internal_model.functions], ["api", "local_helper"])

    def test_build_program_model_can_extract_ir_from_preprocessed_macro_expansion(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            header = root / "api.h"
            source = root / "api.c"

            header.write_text(
                """
typedef struct Leaf {
    int b;
} Leaf;

typedef struct Child {
    Leaf *a;
} Child;

typedef struct Root {
    Child *c;
} Root;

int read_macro_path(Root *z);
""",
                encoding="utf-8",
            )
            source.write_text(
                """
#include "api.h"

#define DO_SOMETHING(x) z->c->x

int read_macro_path(Root *z) {
    return DO_SOMETHING(a->b);
}
""",
                encoding="utf-8",
            )

            model = build_program_model(
                ProgramInput(
                    header_path=header,
                    source_path=str(source),
                    include_dir=str(root),
                    preprocess_ir=True,
                )
            )

        self.assertFalse(model.fallback_used)
        self.assertIsNotNone(model.ir_source_text)
        self.assertIn("return z->c->a->b;", model.ir_source_text)
        statements = model.function_irs["read_macro_path"].statements
        returns = [stmt for stmt in statements if isinstance(stmt, ReturnStmt)]
        self.assertEqual(len(returns), 1)
        self.assertEqual(value_expr(returns[0].value), "z->c->a->b")


if __name__ == "__main__":
    unittest.main()
