from __future__ import annotations

import sys
from dataclasses import dataclass, field
from pathlib import Path

from ..acsl import ACSLSpec, AcslParser, ScannerAcslParser
from ..ast.model import CFunction, CTypeCatalog
from ..compat.source_fallbacks import (
    fallback_build_type_catalog,
    fallback_function_accepts_null_param,
    fallback_function_decl_map,
    fallback_parse_header,
)
from ..ir.clang_json import (
    parse_primary_source_function_names,
    parse_header_function_decls,
    parse_translation_unit_with_decls_and_types,
)
from ..ir.diagnostics import IrDiagnostic
from ..ir.model import FunctionIR
from ..ir.preprocess import PreprocessWorkspace, preprocess_source
from ..shaping.ir_nullability import accepts_null_param_from_ir
from ..source_discovery import (
    collect_source_include_headers,
    collect_visible_headers,
    dedupe_paths,
    source_include_names,
    suggest_extra_sources,
)


@dataclass(frozen=True)
class ProgramInput:
    header_path:     Path
    source_path:     str
    include_dir:     str
    extra_includes:  tuple[str, ...] = ()
    extra_sources:   tuple[str, ...] = ()
    ir_backend:      str = "clang-json"
    preprocess_ir:   bool = False
    include_static_functions: bool = False
    acsl_parser:     AcslParser | None = None
    shaping_features: frozenset[str] = frozenset()


@dataclass
class ProgramModel:
    header_path:     Path
    source_path:     str
    include_dir:     str
    include_roots:   list[Path]
    extra_includes:  list[str]
    extra_sources:   list[str]
    header_text:     str
    source_text:     str
    source_include_names: set[str]
    functions:       list[CFunction]
    acsl_specs:      dict[str, ACSLSpec]
    public_functions: list[CFunction] = field(default_factory=list)
    internal_functions: list[CFunction] = field(default_factory=list)
    ir_source_path:   str | None = None
    ir_source_text:   str | None = None
    function_irs:    dict[str, FunctionIR] = field(default_factory=dict)
    function_decls:  dict[str, CFunction] = field(default_factory=dict)
    type_catalog:    CTypeCatalog = field(default_factory=CTypeCatalog)
    diagnostics:     list[IrDiagnostic] = field(default_factory=list)
    fallback_notes:  list[str] = field(default_factory=list)
    used_source_metadata_fallback: bool = False
    shaping_features: frozenset[str] = frozenset()

    @property
    def fallback_used(self) -> bool:
        return bool(self.fallback_notes)

    def source_text_for_fallbacks(self) -> str | None:
        if self.used_source_metadata_fallback:
            return self.source_text
        if "regex-fallbacks" in self.shaping_features:
            return self.source_text
        return None

    def function_ir(self, function_name: str) -> FunctionIR | None:
        return self.function_irs.get(function_name)

    def function_decl(self, function_name: str) -> CFunction | None:
        return self.function_decls.get(function_name)

    def accepts_null_param(self, function_name: str, param_name: str) -> bool:
        function_ir = self.function_ir(function_name)
        if function_ir is not None:
            return accepts_null_param_from_ir(function_ir, param_name)
        return fallback_function_accepts_null_param(
            self.source_text_for_fallbacks(),
            function_name,
            param_name,
        )

    def fallback_fact_dicts(
        self,
        function_name: str,
        candidate_name: str | None = None,
        candidate_origin: str | None = None,
    ) -> list[dict[str, str]]:
        facts: list[dict[str, str]] = []
        for note in self.fallback_notes:
            facts.append({
                "kind": "fallback",
                "scope": "function",
                "function": function_name,
                "reason": note,
            })
        if candidate_name and candidate_origin == "regex":
            facts.append({
                "kind": "fallback",
                "scope": "candidate",
                "function": function_name,
                "candidate": candidate_name,
                "reason": "candidate generated by regex/source-text shaper",
            })
        return facts

    def print_fallback_warnings(self) -> None:
        for note in self.fallback_notes:
            print(f"kleva synth warning: {note}", file=sys.stderr)


def build_program_model(inputs: ProgramInput) -> ProgramModel:
    header_path = inputs.header_path
    header_text = header_path.read_text()
    parser = inputs.acsl_parser or ScannerAcslParser()
    acsl_specs = parser.parse_file(header_path)
    include_roots = [
        Path(inputs.include_dir),
        *(Path(p) for p in inputs.extra_includes),
    ]
    fallback_notes: list[str] = []

    public_functions = _load_header_functions(
        header_path,
        include_roots,
        inputs.ir_backend,
        fallback_notes,
    )
    functions = list(public_functions)

    extra_sources = list(inputs.extra_sources)
    for suggested in suggest_extra_sources(header_path, include_roots, inputs.source_path):
        if suggested not in extra_sources:
            extra_sources.append(suggested)
    extra_sources = dedupe_paths(extra_sources)

    source_text = _collect_visible_source_text(
        header_path,
        header_text,
        inputs.source_path,
        include_roots,
        extra_sources,
    )

    function_irs: dict[str, FunctionIR] = {}
    function_decls: dict[str, CFunction] = {}
    primary_function_names: set[str] = set()
    primary_target_function_names: set[str] = set()
    type_catalog = CTypeCatalog()
    diagnostics: list[IrDiagnostic] = []
    needs_source_metadata_fallback = inputs.ir_backend == "off"
    if needs_source_metadata_fallback:
        fallback_notes.append(
            "function/type metadata parsed with source-text fallback because IR backend is off"
        )

    preprocess_workspace: PreprocessWorkspace | None = None
    ir_source_path = inputs.source_path
    ir_source_text: str | None = None
    extra_ir_sources = list(extra_sources)
    if inputs.preprocess_ir and inputs.ir_backend == "clang-json":
        preprocess_workspace = PreprocessWorkspace()
        try:
            preprocessed = preprocess_source(
                inputs.source_path,
                [str(p) for p in include_roots],
                out_dir=preprocess_workspace.path,
            )
            ir_source_path = str(preprocessed.path)
            ir_source_text = preprocessed.text
            preprocessed_extras: list[str] = []
            for extra_source in extra_sources:
                extra_preprocessed = preprocess_source(
                    extra_source,
                    [str(p) for p in include_roots],
                    out_dir=preprocess_workspace.path,
                )
                preprocessed_extras.append(str(extra_preprocessed.path))
            extra_ir_sources = preprocessed_extras
            diagnostics.append(IrDiagnostic("preprocess", inputs.source_path, "ok"))
        except Exception as exc:
            diagnostics.append(
                IrDiagnostic(
                    "preprocess",
                    inputs.source_path,
                    "failed",
                    error=f"{type(exc).__name__}: {exc}",
                )
            )
            fallback_notes.append(
                "preprocessed IR disabled after preprocessing failure: "
                f"{type(exc).__name__}: {exc}"
            )
            ir_source_path = inputs.source_path
            extra_ir_sources = list(extra_sources)

    if inputs.ir_backend == "clang-json":
        try:
            function_irs, function_decls, type_catalog = (
                parse_translation_unit_with_decls_and_types(
                    ir_source_path,
                    [str(p) for p in include_roots],
                )
            )
            primary_function_names = set(function_irs)
            try:
                primary_target_function_names = parse_primary_source_function_names(
                    inputs.source_path,
                    [str(p) for p in include_roots],
                )
            except Exception as exc:
                fallback_notes.append(
                    "primary-source function ownership filter disabled after "
                    f"clang-json failure: {type(exc).__name__}: {exc}"
                )
            for extra_source in extra_ir_sources:
                try:
                    _extra_irs, extra_decls, extra_catalog = (
                        parse_translation_unit_with_decls_and_types(
                            extra_source,
                            [str(p) for p in include_roots],
                        )
                    )
                    function_irs.update(_extra_irs)
                    function_decls.update(extra_decls)
                    type_catalog = merge_type_catalogs(type_catalog, extra_catalog)
                except Exception as exc:
                    fallback_notes.append(
                        f"extra source skipped after clang-json failure: {extra_source}: "
                        f"{type(exc).__name__}: {exc}"
                    )
            diagnostics.append(IrDiagnostic("clang-json", ir_source_path, "ok"))
        except Exception as exc:
            diagnostics.append(
                IrDiagnostic(
                    "clang-json",
                    ir_source_path,
                    "failed",
                    error=f"{type(exc).__name__}: {exc}",
                )
            )
            needs_source_metadata_fallback = True
            fallback_notes.append(
                "function/type metadata parsed with source-text fallback after "
                f"clang-json failure: {type(exc).__name__}: {exc}"
            )
    elif inputs.ir_backend != "off":
        raise ValueError(f"unknown IR backend: {inputs.ir_backend}")
    else:
        diagnostics.append(IrDiagnostic("off", inputs.source_path, "disabled"))

    if needs_source_metadata_fallback:
        type_catalog = merge_type_catalogs(
            type_catalog,
            fallback_build_type_catalog(source_text),
        )
        function_decls.update(fallback_function_decl_map(source_text))
    if "regex-fallbacks" in inputs.shaping_features:
        fallback_notes.append("source-text branch shapers enabled by regex-fallbacks feature")

    internal_functions: list[CFunction] = []
    if inputs.include_static_functions:
        public_names = {func.name for func in public_functions}
        seen_names = set(public_names)
        internal_target_names = primary_target_function_names or primary_function_names
        for name in sorted(internal_target_names):
            if name in seen_names:
                continue
            decl = function_decls.get(name)
            if decl is None:
                continue
            if decl.name.upper() == decl.name or decl.name.startswith("__"):
                continue
            internal_functions.append(decl)
            functions.append(decl)
            seen_names.add(name)

    fallback_notes = _unique(fallback_notes)
    diagnostics.extend(
        IrDiagnostic("source-fallback", inputs.source_path, "used", error=note)
        for note in fallback_notes
    )

    model = ProgramModel(
        header_path=header_path,
        source_path=inputs.source_path,
        include_dir=inputs.include_dir,
        include_roots=include_roots,
        extra_includes=list(inputs.extra_includes),
        extra_sources=extra_sources,
        header_text=header_text,
        source_text=source_text,
        ir_source_path=None,
        ir_source_text=ir_source_text,
        source_include_names=source_include_names(inputs.source_path, include_roots),
        functions=functions,
        public_functions=public_functions,
        internal_functions=internal_functions,
        acsl_specs=acsl_specs,
        function_irs=function_irs,
        function_decls=function_decls,
        type_catalog=type_catalog,
        diagnostics=diagnostics,
        fallback_notes=fallback_notes,
        used_source_metadata_fallback=needs_source_metadata_fallback,
        shaping_features=inputs.shaping_features,
    )
    if preprocess_workspace is not None:
        # Keep a real string copy of the preprocessed source in the model and
        # release the temporary file tree after clang has consumed it.
        preprocess_workspace.cleanup()
    return model


def merge_type_catalogs(fallback: CTypeCatalog, preferred: CTypeCatalog) -> CTypeCatalog:
    merged = CTypeCatalog(
        complete_structs=set(fallback.complete_structs),
        opaque_structs=set(fallback.opaque_structs),
        function_pointers=dict(fallback.function_pointers),
        struct_fields={name: dict(fields) for name, fields in fallback.struct_fields.items()},
    )
    merged.complete_structs.update(preferred.complete_structs)
    merged.opaque_structs.update(preferred.opaque_structs)
    merged.function_pointers.update(preferred.function_pointers)
    for name, fields in preferred.struct_fields.items():
        merged.struct_fields[name] = dict(fields)
    merged.opaque_structs.difference_update(merged.complete_structs)
    return merged


def _load_header_functions(
    header_path: Path,
    include_roots: list[Path],
    ir_backend: str,
    fallback_notes: list[str],
) -> list[CFunction]:
    try:
        if ir_backend == "clang-json":
            return parse_header_function_decls(header_path, [str(p) for p in include_roots])
        if ir_backend == "off":
            fallback_notes.append(
                "header declarations parsed with source-text fallback because IR backend is off"
            )
            return fallback_parse_header(header_path)
        raise ValueError(f"unknown IR backend: {ir_backend}")
    except Exception as exc:
        fallback_notes.append(
            "header declarations parsed with source-text fallback after "
            f"clang-json failure: {type(exc).__name__}: {exc}"
        )
        return fallback_parse_header(header_path)


def _collect_visible_source_text(
    header_path: Path,
    header_text: str,
    source_path: str,
    include_roots: list[Path],
    extra_sources: list[str],
) -> str:
    visible_text_parts = collect_visible_headers(header_path, include_roots)
    visible_text_parts.extend(collect_source_include_headers(source_path, include_roots))
    if not visible_text_parts:
        visible_text_parts = [header_text]
    for candidate in [source_path, *extra_sources]:
        try:
            visible_text_parts.append(Path(candidate).read_text())
        except FileNotFoundError:
            pass
    return "\n".join(visible_text_parts)


def _unique(items: list[str]) -> list[str]:
    seen: set[str] = set()
    return [item for item in items if not (item in seen or seen.add(item))]
