"""
codegen.py — Emit C source for the EVA probe driver and the unit test file.

Two outputs
───────────
  Probe driver  (eva/probe.c)
    • One static void probe_<fn_id>(void) per Recipe.
    • Concrete inputs only — no //@ assert annotations.
    • Frama-C EVA abstract-interprets this to produce singleton output values.
    • __GUARD__ markers expand to early-return guards (if (!p) return;).

  Unit test file  (unit/test_gen.c)
    • One static void test_<fn_id>(void) per Recipe.
    • __GUARD__ markers expand to assert(p != NULL).
    • For each output variable, EVA must prove a singleton value V:
          assert(var == V);  /* EVA-proven oracle */
      Otherwise unit generation fails. KLEVA never emits tests without oracles.
    • main() calls all tests and prints "All unit tests passed." on success.
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path

from .config import FunctionSpec, InputSpec
from .recipe import Recipe, expand_guard


# ── file headers ──────────────────────────────────────────────────────────────

_PROBE_HEADER = """\
/* AUTO-GENERATED by kleva (KLEE + EVA) — DO NOT EDIT
 * EVA probe driver: concrete inputs, no //@ assert.
 * Frama-C EVA abstract-interprets this to produce singleton output values.
 * Generated: {ts}
 */
#include <stdint.h>
#include <string.h>
#include "{header}"

"""

_UNIT_HEADER = """\
/* AUTO-GENERATED by kleva (KLEE + EVA) — DO NOT EDIT
 * Oracle values are EVA-proven singletons — not hand-written expected values.
 * Re-generate: kleva gen <module.yaml>
 * Generated: {ts}
 */
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "{header}"

"""

_KLEE_HEADER = """\
/* AUTO-GENERATED by kleva (KLEE + EVA) — DO NOT EDIT
 * KLEE harness for: {func_name}
 * No klee_assert() needed — KLEE detects memory errors automatically.
 * Re-generate: kleva klee <module.yaml>
 * Generated: {ts}
 */
#include <klee/klee.h>
#include <string.h>
#include "{header}"

"""


# ── per-function generators ───────────────────────────────────────────────────

def _probe_fn(recipe: Recipe) -> tuple[str, str]:
    """Return (C source, function name) for one probe function."""
    fn    = "probe_" + recipe.fn_id
    lines = [f"static void {fn}(void) {{"]
    for line in recipe.decl_lines:
        lines.append("    " + line)
    for line in recipe.body_lines:
        lines.append("    " + expand_guard(line, is_probe=True))
    # EVA probes exist only to harvest singleton values at the end of the
    # wrapper. Cleanup can free or mutate objects referenced by output vars,
    # which makes Frama-C report the wrapper as non-terminating or loses the
    # final local values. Unit tests and KLEE harnesses still emit cleanup.
    lines.append("}")
    return "\n".join(lines), fn


def _unit_fn(
    recipe:     Recipe,
    singletons: dict[str, int],
) -> tuple[str, str, list[str], list[str]]:
    """
    Return (C source, fn_name, proven_vars, unproven_vars) for one unit test.
    """
    fn             = "test_" + recipe.fn_id
    proven:   list[str] = []
    unproven: list[str] = []

    lines = [f"static void {fn}(void) {{"]
    for line in recipe.decl_lines:
        lines.append("    " + line)
    for line in recipe.body_lines:
        lines.append("    " + expand_guard(line, is_probe=False))

    for var in recipe.outputs:
        if var in singletons:
            proven.append(var)
            lines.append(
                f"    assert({var} == {singletons[var]}); /* EVA-proven oracle */"
            )
        else:
            unproven.append(var)

    for line in recipe.cleanup:
        lines.append("    " + line)
    lines.append(f'    printf("PASS {fn}\\n");')
    lines.append("}")
    return "\n".join(lines), fn, proven, unproven


# ── file writers ──────────────────────────────────────────────────────────────

def write_probe_driver(
    recipes: list[Recipe],
    path:    str,
    header:  str,
    ts:      str | None = None,
) -> list[str]:
    """
    Write the EVA probe driver C file.
    Returns the list of probe function names (in call order).
    """
    ts = ts or datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    bodies:   list[str] = []
    fn_names: list[str] = []

    for r in recipes:
        body, fn = _probe_fn(r)
        bodies.append(body)
        fn_names.append(fn)

    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write(_PROBE_HEADER.format(ts=ts, header=header))
        seen_preamble: set[str] = set()
        preamble_lines: list[str] = []
        for r in recipes:
            for line in r.preamble:
                if line not in seen_preamble:
                    seen_preamble.add(line)
                    preamble_lines.append(line)
        if preamble_lines:
            for line in preamble_lines:
                f.write(line + "\n")
            f.write("\n")
        f.write("\n\n".join(bodies))
        f.write("\n\nint main(void) {\n")
        for fn in fn_names:
            f.write(f"    {fn}();\n")
        f.write("    return 0;\n}\n")

    return fn_names


def write_probe_standalone(
    recipe: Recipe,
    path:   str,
    header: str,
    ts:     str | None = None,
) -> None:
    """
    Write a single-recipe probe C file with its own main().

    Used for per-probe EVA runs: each file has exactly one probe function so
    Frama-C starts with a clean heap and never accumulates abstract state from
    previous probes (which degrades singleton precision for later functions).
    """
    ts = ts or datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    body, fn = _probe_fn(recipe)
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write(_PROBE_HEADER.format(ts=ts, header=header))
        for pline in recipe.preamble:
            f.write(pline + "\n")
        if recipe.preamble:
            f.write("\n")
        f.write(body)
        f.write(f"\n\nint main(void) {{\n    {fn}();\n    return 0;\n}}\n")


def write_unit_tests(
    recipes:             list[Recipe],
    singletons_by_probe: dict[str, dict[str, int]],
    path:                str,
    header:              str,
    ts:                  str | None = None,
) -> tuple[int, int]:
    """
    Write the unit test C file.
    Returns (total_proven_assertions, total_unproven).

    A configured output without an EVA singleton is a hard failure. Emitting a
    unit test that only executes code and prints PASS would give a false sense
    of verification.
    """
    ts = ts or datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    bodies:   list[str] = []
    fn_names: list[str] = []
    total_proven = total_unproven = 0

    for r in recipes:
        probe_fn   = "probe_" + r.fn_id
        singletons = singletons_by_probe.get(probe_fn, {})
        body, fn, proven, unproven = _unit_fn(r, singletons)
        if unproven:
            missing = ", ".join(unproven)
            raise ValueError(
                f"EVA did not prove singleton(s) for {r.fn_id}: {missing}"
            )
        bodies.append(body)
        fn_names.append(fn)
        total_proven   += len(proven)
        total_unproven += len(unproven)

    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write(_UNIT_HEADER.format(ts=ts, header=header))
        # Emit preamble declarations (static helpers, etc.) deduplicated.
        seen_preamble: set[str] = set()
        preamble_lines: list[str] = []
        for r in recipes:
            for line in r.preamble:
                if line not in seen_preamble:
                    seen_preamble.add(line)
                    preamble_lines.append(line)
        if preamble_lines:
            for line in preamble_lines:
                f.write(line + "\n")
            f.write("\n")
        f.write("\n\n".join(bodies))
        f.write("\n\nint main(void) {\n")
        for fn in fn_names:
            f.write(f"    {fn}();\n")
        f.write('\n    printf("\\nAll unit tests passed.\\n");\n')
        f.write("    return 0;\n}\n")

    return total_proven, total_unproven


# ── KLEE harness writer ───────────────────────────────────────────────────────

def write_klee_harness(
    spec:   FunctionSpec,
    path:   str,
    header: str,
    ts:     str | None = None,
) -> None:
    """
    Generate a KLEE harness C file for one function.

    Structure:
        1. Symbolic declarations  — one per InputSpec
             scalar: declare + klee_make_symbolic(&var, sizeof, name) + klee_assume()
             array:  declare[symbolic_size] + klee_make_symbolic(arr, size, name)
        2. Call sequence  — spec.body with __GUARD__ → early-return guards
        3. Cleanup        — spec.cleanup

    No klee_assert() is needed.  KLEE automatically detects:
        • out-of-bounds memory accesses
        • use-after-free / double-free
        • division by zero
        • calls to klee_assert() if you add them manually later
    """
    ts = ts or datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines: list[str] = [_KLEE_HEADER.format(func_name=spec.name, header=header, ts=ts)]
    for preamble_line in spec.preamble:
        lines.append(preamble_line)
    if spec.preamble:
        lines.append("")
    lines.append("int main(void) {")
    lines.append("    /* --- symbolic inputs --- */")

    for inp in spec.inputs:
        if inp.c_type.endswith("[]"):
            # Array: fixed-size symbolic buffer
            n = inp.symbolic_size or inp.max_length or 256
            lines.append(f"    uint8_t {inp.c_var}[{n}];")
            lines.append(
                f'    klee_make_symbolic({inp.c_var}, {n}, "{inp.ktest_name}");'
            )
            # assume conditions apply to arrays too (e.g. length constraints
            # are expressed on the scalar length var, not the array itself)
        else:
            # Scalar: address-of make_symbolic
            lines.append(f"    {inp.c_type} {inp.c_var};")
            lines.append(
                f'    klee_make_symbolic(&{inp.c_var}, sizeof({inp.c_var}), '
                f'"{inp.ktest_name}");'
            )
            # bounds → klee_assume (preferred: min/max declared in YAML)
            if inp.bounds is not None:
                if inp.bounds.min is not None:
                    lines.append(f"    klee_assume({inp.c_var} >= {inp.bounds.min});")
                if inp.bounds.max is not None:
                    lines.append(f"    klee_assume({inp.c_var} <= {inp.bounds.max});")
            # assume → klee_assume (advanced: raw C expressions)
            for cond in inp.assume:
                lines.append(f"    klee_assume({cond});")

    lines.append("")
    lines.append("    /* --- call sequence --- */")

    for line in spec.body:
        lines.append("    " + expand_guard(line, is_probe=True, is_klee=True))
    for line in spec.cleanup:
        lines.append("    " + line)

    lines.append("    return 0;")
    lines.append("}")

    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
