"""
codegen.py — Emit C source for the EVA probe driver and the unit test file.

Two outputs
───────────
  Probe driver  (eva/probe.c)
    • One static void probe_<fn_id>(void) per Recipe.
    • Concrete inputs only — no //@ assert annotations.
    • Frama-C EVA abstract-interprets this to produce singleton output values.
    • __GUARD__ markers expand to Frama_C_assume() fixture assumptions.

  Unit test file  (unit/test_gen.c)
    • One static void test_<fn_id>(void) per Recipe.
    • __GUARD__ markers expand to assert(p != NULL).
    • For each output variable, EVA must prove a singleton value V:
          assert(var == V);  /* EVA-proven oracle */
      Otherwise unit generation fails unless diagnostic unproved output is
      explicitly requested. Diagnostic tests are emitted separately and never
      pretend to be proven regression tests.
    • main() calls all tests and prints "All unit tests passed." on success.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from .config import FunctionSpec, InputSpec
from .recipe import Recipe, expand_guard


@dataclass(frozen=True)
class UnprovedClassification:
    category: str
    note:     str


@dataclass(frozen=True)
class KleeDiagnostic:
    status:   str
    artifact: str


# ── file headers ──────────────────────────────────────────────────────────────

_PROBE_HEADER = """\
/* AUTO-GENERATED by kleva (KLEE + EVA) — DO NOT EDIT
 * EVA probe driver: concrete inputs, no //@ assert.
 * Frama-C EVA abstract-interprets this to produce singleton output values.
 * Generated: {ts}
 */
#include <stdint.h>
#include <string.h>
#include "{header}"

void Frama_C_assume(int condition);

"""

_UNIT_HEADER = """\
/* AUTO-GENERATED by kleva (KLEE + EVA) — DO NOT EDIT
 * Oracle values are EVA-proven singletons — not hand-written expected values.
 * Re-generate: kleva gen <module.yaml>
 * Generated: {ts}
 */
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "{header}"

"""

_UNPROVED_HEADER = """\
/* AUTO-GENERATED by kleva (KLEE + EVA) — DO NOT EDIT
 * Diagnostic candidate tests whose requested outputs were not fully
 * EVA-proven singletons. These are review artifacts, not trusted regression
 * oracles.
 * Re-generate: kleva gen <module.yaml> --emit-unproved=tests
 * Generated: {ts}
 */
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "{header}"

"""

_KLEE_HEADER = """\
/* AUTO-GENERATED by kleva (KLEE + EVA) — DO NOT EDIT
 * KLEE harness for: {func_name}
 * No klee_assert() needed — KLEE detects memory errors automatically.
 * Re-generate: kleva klee <module.yaml>
 * Generated: {ts}
 */
#include <klee/klee.h>
#include <string.h>
#include "{header}"

"""


# ── per-function generators ───────────────────────────────────────────────────

def _drop_local_typedefs(lines: list[str]) -> list[str]:
    out: list[str] = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("typedef "):
            continue
        out.append(line)
    return out


def _probe_fn(recipe: Recipe) -> tuple[str, str]:
    """Return (C source, function name) for one probe function."""
    fn    = "probe_" + recipe.fn_id
    lines = [f"static void {fn}(void) {{"]
    for line in recipe.decl_lines:
        lines.append("    " + line)
    for line in _drop_local_typedefs(recipe.body_lines):
        lines.append("    " + expand_guard(line, is_probe=True))
    # EVA probes exist only to harvest singleton values at the end of the
    # wrapper. Cleanup can free or mutate objects referenced by output vars,
    # which makes Frama-C report the wrapper as non-terminating or loses the
    # final local values. Unit tests and KLEE harnesses still emit cleanup.
    lines.append("}")
    return "\n".join(lines), fn


def _unit_fn(
    recipe:     Recipe,
    singletons: dict[str, int],
) -> tuple[str, str, list[str], list[str]]:
    """
    Return (C source, fn_name, proven_vars, unproven_vars) for one unit test.
    """
    fn             = "test_" + recipe.fn_id
    proven:   list[str] = []
    unproven: list[str] = []

    lines = [f"static void {fn}(void) {{"]
    for line in recipe.decl_lines:
        lines.append("    " + line)
    for line in _drop_local_typedefs(recipe.body_lines):
        lines.append("    " + expand_guard(line, is_probe=False))

    for var in recipe.outputs:
        if var in singletons:
            proven.append(var)
            lines.append(
                f"    assert({var} == {singletons[var]}); /* EVA-proven oracle */"
            )
        else:
            unproven.append(var)

    for line in recipe.cleanup:
        lines.append("    " + line)
    lines.append(f'    printf("PASS {fn}\\n");')
    lines.append("}")
    return "\n".join(lines), fn, proven, unproven


def _diagnostic_unit_fn(
    recipe:     Recipe,
    singletons: dict[str, int],
    unproven:   list[str],
) -> tuple[str, str]:
    """
    Return (C source, fn_name) for an unproved diagnostic test.

    Proven outputs still get assertions. Unproved outputs are deliberately not
    asserted; the generated comments are there so humans can triage whether the
    gap is ACSL, fixture shaping, EVA precision, or a possible implementation
    bug.
    """
    fn = "test_" + recipe.fn_id
    classification = _classify_unproved(recipe, singletons, unproven)
    klee_diag = _klee_diagnostic(recipe)
    lines = [
        f"/*",
        f" * KLEVA diagnostic candidate: {recipe.fn_id}",
        f" * Status: EVA_UNPROVED",
        f" * KLEE status: {klee_diag.status}",
        f" * KLEE artifact: {klee_diag.artifact}",
        f" * Source location: {_diagnostic_value(recipe.source_location)}",
        f" * Target branch: {_diagnostic_value(recipe.target_branch)}",
        f" * Candidate origin: {_diagnostic_value(recipe.candidate_origin)}",
        f" * Candidate facts: {_diagnostic_facts(recipe.candidate_facts)}",
        f" * Missing singleton output(s): {', '.join(unproven)}",
        f" * Reason category: {classification.category}",
        f" * Reason note: {classification.note}",
        f" */",
        f"static void {fn}(void) {{",
    ]
    for line in recipe.decl_lines:
        lines.append("    " + line)
    for line in _drop_local_typedefs(recipe.body_lines):
        lines.append("    " + expand_guard(line, is_probe=False))

    for var in recipe.outputs:
        if var in singletons:
            lines.append(
                f"    assert({var} == {singletons[var]}); /* EVA-proven oracle */"
            )
        else:
            lines.append(f"    /* EVA_UNPROVED: {var}; assertion omitted for review. */")

    for line in recipe.cleanup:
        lines.append("    " + line)
    lines.append(f'    printf("DIAG {fn}\\n");')
    lines.append("}")
    return "\n".join(lines), fn


def _klee_diagnostic(recipe: Recipe) -> KleeDiagnostic:
    if recipe.ktest_path:
        return KleeDiagnostic("ktest_available", recipe.ktest_path)
    return KleeDiagnostic("not_recorded", "not_recorded")


def _diagnostic_value(value: str | None) -> str:
    return value if value else "not_recorded"


def _diagnostic_facts(facts: list[dict[str, str]]) -> str:
    if not facts:
        return "not_recorded"
    rendered: list[str] = []
    for fact in facts:
        if fact.get("kind") == "branch":
            rendered.append(
                f"branch:{fact.get('target', '?')} {fact.get('relation', '?')} {fact.get('value', '?')}"
            )
        elif fact.get("kind") == "call":
            rendered.append(
                f"call:{fact.get('callee', '?')} {fact.get('mode', '?')} {fact.get('outcome', '?')}"
            )
        elif fact.get("kind") == "post_state":
            rendered.append(
                f"post:{fact.get('target', '?')} {fact.get('relation', '?')} {fact.get('value', '?')}"
            )
        else:
            rendered.append(str(fact))
    return "; ".join(rendered)


def _classify_unproved(
    recipe:     Recipe,
    singletons: dict[str, int],
    unproven:   list[str],
) -> UnprovedClassification:
    text = "\n".join([*recipe.decl_lines, *recipe.body_lines, *recipe.cleanup, *recipe.preamble])
    lower = text.lower()

    if "kleva synth:" in lower or "no visible allocation strategy" in lower or "using null" in lower:
        return UnprovedClassification(
            "fixture_gap",
            "generated setup contains a visible fixture fallback or missing allocation strategy",
        )

    missing_assignments = [
        var for var in unproven
        if not _looks_assigned_or_declared(var, recipe)
    ]
    if missing_assignments:
        return UnprovedClassification(
            "missing_contract_or_observable",
            f"requested output is not visibly assigned or declared in the generated probe: {', '.join(missing_assignments)}",
        )

    if singletons:
        return UnprovedClassification(
            "eva_imprecision",
            "EVA proved some requested outputs but not all, suggesting a precision or path-splitting gap",
        )

    if any(var in {"out_ret", "ret", "result"} or var.endswith("_ret") for var in unproven):
        return UnprovedClassification(
            "possible_implementation_bug",
            "return-value output stayed unproved for this concrete candidate; review the path for missing setup or unexpected behavior",
        )

    return UnprovedClassification(
        "eva_imprecision_or_missing_contract",
        "no specific fixture or observable-shape issue was detected from the generated recipe",
    )


def _looks_assigned_or_declared(var: str, recipe: Recipe) -> bool:
    text = "\n".join([*recipe.decl_lines, *recipe.body_lines])
    return (
        f" {var} " in text
        or f" {var}=" in text
        or f" {var} =" in text
        or text.strip().startswith(f"{var} ")
    )


# ── file writers ──────────────────────────────────────────────────────────────

def _dedup_preamble_blocks(recipes: list[Recipe]) -> list[str]:
    seen: set[str] = set()
    out:  list[str] = []

    for r in recipes:
        i = 0
        while i < len(r.preamble):
            line = r.preamble[i]
            block = [line]
            if line.startswith("static ") and line.rstrip().endswith("{"):
                depth = line.count("{") - line.count("}")
                i += 1
                while i < len(r.preamble) and depth > 0:
                    block.append(r.preamble[i])
                    depth += r.preamble[i].count("{") - r.preamble[i].count("}")
                    i += 1
            else:
                i += 1

            key = "\n".join(block)
            if key not in seen:
                seen.add(key)
                out.extend(block)

    return out


def write_probe_driver(
    recipes: list[Recipe],
    path:    str,
    header:  str,
    ts:      str | None = None,
) -> list[str]:
    """
    Write the EVA probe driver C file.
    Returns the list of probe function names (in call order).
    """
    ts = ts or datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    bodies:   list[str] = []
    fn_names: list[str] = []

    for r in recipes:
        body, fn = _probe_fn(r)
        bodies.append(body)
        fn_names.append(fn)

    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write(_PROBE_HEADER.format(ts=ts, header=header))
        preamble_lines = _dedup_preamble_blocks(recipes)
        if preamble_lines:
            for line in preamble_lines:
                f.write(line + "\n")
            f.write("\n")
        f.write("\n\n".join(bodies))
        f.write("\n\nint main(void) {\n")
        for fn in fn_names:
            f.write(f"    {fn}();\n")
        f.write("    return 0;\n}\n")

    return fn_names


def write_probe_standalone(
    recipe: Recipe,
    path:   str,
    header: str,
    ts:     str | None = None,
) -> None:
    """
    Write a single-recipe probe C file with its own main().

    Used for per-probe EVA runs: each file has exactly one probe function so
    Frama-C starts with a clean heap and never accumulates abstract state from
    previous probes (which degrades singleton precision for later functions).
    """
    ts = ts or datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    body, fn = _probe_fn(recipe)
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write(_PROBE_HEADER.format(ts=ts, header=header))
        for pline in recipe.preamble:
            f.write(pline + "\n")
        if recipe.preamble:
            f.write("\n")
        f.write(body)
        f.write(f"\n\nint main(void) {{\n    {fn}();\n    return 0;\n}}\n")


def write_unit_tests(
    recipes:             list[Recipe],
    singletons_by_probe: dict[str, dict[str, int]],
    path:                str,
    header:              str,
    ts:                  str | None = None,
    emit_unproved:       str = "off",
) -> tuple[int, int, int]:
    """
    Write the unit test C file.
    Returns (total_proven_assertions, total_unproven, skipped_candidates).

    A configured output without an EVA singleton is a hard failure by default.
    Optional candidate recipes remain search goals, but callers may ask KLEVA
    to emit them as separate diagnostic artifacts for review.
    """
    ts = ts or datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    bodies:   list[str] = []
    fn_names: list[str] = []
    diagnostic_bodies: list[str] = []
    diagnostic_fn_names: list[str] = []
    report_lines: list[str] = []
    total_proven = total_unproven = skipped_candidates = 0
    emit_unproved = emit_unproved or "off"
    if emit_unproved not in {"off", "report", "tests", "all"}:
        raise ValueError(f"unknown emit_unproved mode: {emit_unproved}")

    for r in recipes:
        probe_fn   = "probe_" + r.fn_id
        singletons = singletons_by_probe.get(probe_fn, {})
        body, fn, proven, unproven = _unit_fn(r, singletons)
        if unproven:
            if r.candidate:
                total_unproven += len(unproven)
                if emit_unproved in {"report", "tests", "all"}:
                    classification = _classify_unproved(r, singletons, unproven)
                    klee_diag = _klee_diagnostic(r)
                    report_lines.append(
                        f"- {r.fn_id}: EVA_UNPROVED missing={', '.join(unproven)} "
                        f"klee_status={klee_diag.status} klee_artifact={klee_diag.artifact} "
                        f"source_location={_diagnostic_value(r.source_location)} "
                        f"target_branch={_diagnostic_value(r.target_branch)} "
                        f"candidate_origin={_diagnostic_value(r.candidate_origin)} "
                        f"candidate_facts={_diagnostic_facts(r.candidate_facts)} "
                        f"reason={classification.category} note={classification.note}"
                    )
                if emit_unproved in {"tests", "all"}:
                    diag_body, diag_fn = _diagnostic_unit_fn(r, singletons, unproven)
                    diagnostic_bodies.append(diag_body)
                    diagnostic_fn_names.append(diag_fn)
                else:
                    skipped_candidates += 1
                continue
            missing = ", ".join(unproven)
            raise ValueError(
                f"EVA did not prove singleton(s) for {r.fn_id}: {missing}"
            )
        bodies.append(body)
        fn_names.append(fn)
        total_proven   += len(proven)
        total_unproven += len(unproven)

    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write(_UNIT_HEADER.format(ts=ts, header=header))
        # Emit preamble declarations (static helpers, etc.) deduplicated.
        preamble_lines = _dedup_preamble_blocks(recipes)
        if preamble_lines:
            for line in preamble_lines:
                f.write(line + "\n")
            f.write("\n")
        f.write("\n\n".join(bodies))
        f.write("\n\nint main(void) {\n")
        for fn in fn_names:
            f.write(f"    {fn}();\n")
        f.write('\n    printf("\\nAll unit tests passed.\\n");\n')
        f.write("    return 0;\n}\n")

    if report_lines and emit_unproved in {"report", "all"}:
        report_path = _unproved_report_path(path)
        Path(report_path).parent.mkdir(parents=True, exist_ok=True)
        with open(report_path, "w") as f:
            f.write("# KLEVA Unproved Candidate Report\n\n")
            f.write("These candidates were generated and checked, but EVA did not prove all requested singleton outputs.\n\n")
            for line in report_lines:
                f.write(line + "\n")

    if diagnostic_bodies:
        diagnostic_path = _unproved_test_path(path)
        Path(diagnostic_path).parent.mkdir(parents=True, exist_ok=True)
        with open(diagnostic_path, "w") as f:
            f.write(_UNPROVED_HEADER.format(ts=ts, header=header))
            preamble_lines = _dedup_preamble_blocks([r for r in recipes if r.candidate])
            if preamble_lines:
                for line in preamble_lines:
                    f.write(line + "\n")
                f.write("\n")
            f.write("\n\n".join(diagnostic_bodies))
            f.write("\n\nint main(void) {\n")
            for fn in diagnostic_fn_names:
                f.write(f"    {fn}();\n")
            f.write('\n    printf("\\nDiagnostic unproved candidate tests ran.\\n");\n')
            f.write("    return 0;\n}\n")

    return total_proven, total_unproven, skipped_candidates


def _unproved_test_path(path: str) -> str:
    p = Path(path)
    return str(p.with_name(f"{p.stem}_unproved{p.suffix}"))


def _unproved_report_path(path: str) -> str:
    p = Path(path)
    return str(p.with_name(f"{p.stem}_unproved_report.md"))


# ── KLEE harness writer ───────────────────────────────────────────────────────

def write_klee_harness(
    spec:   FunctionSpec,
    path:   str,
    header: str,
    ts:     str | None = None,
) -> None:
    """
    Generate a KLEE harness C file for one function.

    Structure:
        1. Symbolic declarations  — one per InputSpec
             scalar: declare + klee_make_symbolic(&var, sizeof, name) + klee_assume()
             array:  declare[symbolic_size] + klee_make_symbolic(arr, size, name)
        2. Call sequence  — spec.body with __GUARD__ → early-return guards
        3. Cleanup        — spec.cleanup

    No klee_assert() is needed.  KLEE automatically detects:
        • out-of-bounds memory accesses
        • use-after-free / double-free
        • division by zero
        • calls to klee_assert() if you add them manually later
    """
    ts = ts or datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines: list[str] = [_KLEE_HEADER.format(func_name=spec.name, header=header, ts=ts)]
    for preamble_line in spec.preamble:
        lines.append(preamble_line)
    if spec.preamble:
        lines.append("")
    lines.append("int main(void) {")
    lines.append("    /* --- symbolic inputs --- */")

    for inp in spec.inputs:
        if inp.c_type.endswith("[]"):
            # Array: fixed-size symbolic buffer
            n = inp.symbolic_size or inp.max_length or 256
            lines.append(f"    uint8_t {inp.c_var}[{n}];")
            lines.append(
                f'    klee_make_symbolic({inp.c_var}, {n}, "{inp.ktest_name}");'
            )
            # assume conditions apply to arrays too (e.g. length constraints
            # are expressed on the scalar length var, not the array itself)
        else:
            # Scalar: address-of make_symbolic
            lines.append(f"    {inp.c_type} {inp.c_var};")
            lines.append(
                f'    klee_make_symbolic(&{inp.c_var}, sizeof({inp.c_var}), '
                f'"{inp.ktest_name}");'
            )
            # bounds → klee_assume (preferred: min/max declared in YAML)
            if inp.bounds is not None:
                if inp.bounds.min is not None:
                    lines.append(f"    klee_assume({inp.c_var} >= {inp.bounds.min});")
                if inp.bounds.max is not None:
                    lines.append(f"    klee_assume({inp.c_var} <= {inp.bounds.max});")
            # assume → klee_assume (advanced: raw C expressions)
            for cond in inp.assume:
                lines.append(f"    klee_assume({cond});")

    lines.append("")
    lines.append("    /* --- call sequence --- */")

    for line in _drop_local_typedefs(spec.body):
        lines.append("    " + expand_guard(line, is_probe=True, is_klee=True))
    for line in spec.cleanup:
        lines.append("    " + line)

    lines.append("    return 0;")
    lines.append("}")

    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
